### ISSUE TITLE
public module registry

### ISSUE THREAD

**Issue by ramkumarkoppu** [ARMmbed/uvisor#137]
when commands yotta target frdm-k64f-gcc and yotta install are executed, dependency files are downloading from public module registry:

yotta target frdm-k64f-gcc
info: get versions for frdm-k64f-gcc
info: download frdm-k64f-gcc@2.0.0 from the public module registry
info: get versions for kinetis-k64-gcc
info: download kinetis-k64-gcc@2.0.0 from the public module registry
info: get versions for mbed-gcc
info: download mbed-gcc@1.1.0 from the public module registry

 yotta install
info: get versions for mbed-drivers
info: download mbed-drivers@0.12.0 from the public module registry
info: get versions for cmsis-core
info: download cmsis-core@1.1.2 from the public module registry
info: get versions for cmsis-core-freescale
info: download cmsis-core-freescale@1.0.0 from the public module registry
info: get versions for cmsis-core-k64f
info: download cmsis-core-k64f@1.0.0 from the public module registry
info: get versions for mbed-hal
info: download mbed-hal@1.2.2 from the public module registry
info: get versions for ualloc
info: download ualloc@1.0.3 from the public module registry
info: get versions for minar
info: download minar@1.0.4 from the public module registry
info: get versions for core-util
info: download core-util@1.1.5 from the public module registry
info: get versions for compiler-polyfill
info: download compiler-polyfill@1.2.1 from the public module registry
info: get versions for mbed-hal-freescale
info: download mbed-hal-freescale@1.0.0 from the public module registry
info: get versions for mbed-hal-ksdk-mcu
info: download mbed-hal-ksdk-mcu@1.0.8 from the public module registry
info: get versions for mbed-hal-k64f
info: download mbed-hal-k64f@1.0.1 from the public module registry
info: get versions for mbed-hal-frdm-k64f
info: download mbed-hal-frdm-k64f@1.0.0 from the public module registry
info: get versions for dlmalloc
info: download dlmalloc@1.0.0 from the public module registry
info: get versions for minar-platform
info: download minar-platform@1.0.0 from the public module registry
info: get versions for minar-platform-mbed
info: download minar-platform-mbed@1.0.0 from the public module registry
error: mbed-drivers does not meet specification ~0.11.1 required by core-util

The question is how to have all these required modules locally installed instead of downloading from public module registry?
and also it throws error:
error: mbed-drivers does not meet specification ~0.11.1 required by core-util

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1931

**Comment by meriac** [comment]
Hi @ramkumarkoppu,

I believe this is fixed since you posted your bug report:

milmer01@localhost:~/temp/uvisor-helloworld$ yotta target frdm-k64f-gcc
info: get versions for frdm-k64f-gcc
info: download frdm-k64f-gcc@2.0.0 from the public module registry
info: get versions for kinetis-k64-gcc
info: download kinetis-k64-gcc@2.0.0 from the public module registry
info: get versions for mbed-gcc
info: download mbed-gcc@1.1.0 from the public module registry
milmer01@localhost:~/temp/uvisor-helloworld$ yotta install
info: get versions for uvisor-lib
info: download uvisor-lib@1.0.12 from the public module registry
info: get versions for mbed-drivers
info: download mbed-drivers@0.12.0 from the public module registry
info: get versions for cmsis-core
info: download cmsis-core@1.1.2 from the public module registry
info: get versions for cmsis-core-freescale
info: download cmsis-core-freescale@1.0.0 from the public module registry
info: get versions for cmsis-core-k64f
info: download cmsis-core-k64f@1.0.0 from the public module registry
info: get versions for mbed-hal
info: download mbed-hal@1.2.2 from the public module registry
info: get versions for ualloc
info: download ualloc@1.0.3 from the public module registry
info: get versions for minar
info: download minar@1.0.4 from the public module registry
info: get versions for core-util
info: download core-util@1.2.0 from the public module registry
info: get versions for compiler-polyfill
info: download compiler-polyfill@1.2.1 from the public module registry
info: get versions for mbed-hal-freescale
info: download mbed-hal-freescale@1.0.0 from the public module registry
info: get versions for mbed-hal-ksdk-mcu
info: download mbed-hal-ksdk-mcu@1.0.8 from the public module registry
info: get versions for mbed-hal-k64f
info: download mbed-hal-k64f@1.0.1 from the public module registry
info: get versions for mbed-hal-frdm-k64f
info: download mbed-hal-frdm-k64f@1.0.0 from the public module registry
info: get versions for dlmalloc
info: download dlmalloc@1.0.0 from the public module registry
info: get versions for minar-platform
info: download minar-platform@1.0.0 from the public module registry
info: get versions for minar-platform-mbed
info: download minar-platform-mbed@1.1.0 from the public module registry
